{{- if and .Values.global.modules.publicDomainTemplate .Values.global.clusterIsBootstrapped }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  namespace: test-ext-modules
  {{- include "helm_lib_module_labels" (list . (dict "app" "hello-world")) | nindent 2 }}
spec:
  ingressClassName: {{ include "helm_lib_module_ingress_class" . | quote }}
  rules:
    - host: {{ include "helm_lib_module_public_domain" (list . "hello") }}
      http:
        paths:
          - backend:
              service:
                name: hello-world
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  {{- if (include "helm_lib_module_https_ingress_tls_enabled" .) }}
  tls:
    - hosts:
        - {{ include "helm_lib_module_public_domain" (list . "hello") }}
      secretName: {{ include "helm_lib_module_https_secret_name" (list . "ingress-tls") }}
  {{- end }}
{{- if eq (include "helm_lib_module_https_mode" .) "CertManager" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-world
  namespace: test-ext-modules
  {{- include "helm_lib_module_labels" (list . (dict "app" "hello-world")) | nindent 2 }}
spec:
  certificateOwnerRef: false
  secretName: {{ include "helm_lib_module_https_secret_name" (list . "ingress-tls") }}
  commonName: {{ include "helm_lib_module_public_domain" (list . "hello") }}
  dnsNames:
    - {{ include "helm_lib_module_public_domain" (list . "hello") }}
  issuerRef:
    name: {{ include "helm_lib_module_https_cert_manager_cluster_issuer_name" . }}
    kind: ClusterIssuer
{{- end }}
---
{{- end }}
