{{- if .Values.helloWorld.registry }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockercfg
metadata:
  name: registrysecret
  namespace: test-ext-modules
data:
  .dockercfg: {{ .Values.helloWorld.registry.dockercfg }}
{{- end }}
