apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: test-ext-modules
  {{- include "helm_lib_module_labels" (list . (dict "app" "hello-world")) | nindent 2 }}
spec:
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
