name: Deploy

on:
  workflow_dispatch:
   inputs:
      release_channel:
        description: "Select the release channel"
        type: choice
        default: alpha
        options:
          - "alpha"
          - "beta"
          - "early-access"
          - "stable"
          - "rock-solid"
      tag:
        description: "Tag of the module, e.g., v1.21.1"
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy the module
    steps:
      - uses: actions/checkout@v4

      - uses: deckhouse/modules-actions/setup@v1
        with:
          registry: ghcr.io
          registry_login: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

      - uses: deckhouse/modules-actions/deploy@v1
        with:
          module_source: ghcr.io/${{ github.actor }}
          module_name: mymodule
          module_tag: ${{ github.ref_name }}
          release_channel: ${{ github.event.inputs.release_channel }}